name: windows

services:
  windows:
    image: docker.io/dockurr/windows:4.35
    container_name: windows7
    environment:
      VERSION: "7e"
      DISK_SIZE: "80G"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      USERNAME: "admin"
      PASSWORD: "admin"
      LANGUAGE: "English"
      REGION: "en-US"
      KEYBOARD: "en-US"
      # KEY: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: no
    stop_grace_period: 2m
