name: prometheus

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - prom_data:/prometheus

volumes:
  prom_data:
