name: keycloak

services:
  keycloak:
    image: docker.io/keycloak/keycloak:25.0
    container_name: keycloak
    command:
      - start-dev
    ports:
      - 8080:8080
    restart: always
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  keycloak_data:
