name: firefox-tigervnc

services:
  firefox-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    image: firefox-tigervnc:1.0.0
    container_name: firefox-tigervnc
    ports:
      - 6100:6100
    restart: unless-stopped
    environment:
      - DISPLAY=:200
      - RESOLUTION=1920x1080
    volumes:
      - firefox-data:/home/firefoxuser/.mozilla/firefox

volumes:
  firefox-data:
