name: prometheus-grafana

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.55.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/:ro,Z
      - prom_data:/prometheus
    networks:
      - pg_net

  grafana:
    image: docker.io/grafana/grafana:7.5.15
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - AWS_SDK_LOAD_CONFIG=true
      - GF_AUTH_SIGV4_AUTH_ENABLED=true
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro,Z
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro,Z
      - grafana_data:/var/lib/grafana
    networks:
      - pg_net

volumes:
  prom_data:
  grafana_data:

networks:
  pg_net:
    driver: bridge
