name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - jenkins_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
