name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins_config.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./casc/jenkins_config.yaml:/var/jenkins_home/casc/jenkins_config.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - jenkins_net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    command: >
      /bin/bash -c
      "/usr/bin/jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt && exec /usr/local/bin/jenkins.sh"

  # agent1:
  #   image: jenkins/inbound-agent:jdk17
  #   container_name: jenkins-agent-1
  #   restart: always
  #   environment:
  #     - JENKINS_URL=http://jenkins:8080
  #     - JENKINS_AGENT_NAME=node-1
  #     - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
  #     - JENKINS_SECRET=node-1-secret
  #   depends_on:
  #     - jenkins
  #   networks:
  #     - jenkins_net

  # agent2:
  #   image: jenkins/inbound-agent:jdk17
  #   container_name: jenkins-agent-2
  #   restart: always
  #   environment:
  #     - JENKINS_URL=http://jenkins:8080
  #     - JENKINS_AGENT_NAME=node-2
  #     - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
  #     - JENKINS_SECRET=node-1-secret
  #   depends_on:
  #     - jenkins
  #   networks:
  #     - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
