jenkins:
  # systemMessage: "Automated Jenkins setup using Docker and JCasC"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "developer"
          password: "developer"
        - id: "viewer"
          password: "viewer"

  nodes:
    - permanent:
        mode: NORMAL
        name: "node-1"
        labelString: "node-1"
        remoteFS: "/home/node-1"
        numExecutors: 2
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"
    - permanent:
        mode: NORMAL
        name: "node-2"
        labelString: "node-2"
        remoteFS: "/home/node-2"
        numExecutors: 2
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

unclassified:
  location:
    adminAddress: "admin@jenkins.local"
    url: http://127.0.0.1:8080/

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"
