jenkins:
  systemMessage: "Automated Jenkins setup using Docker and JCasC"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "developer"
          password: "developer"
        - id: "viewer"
          password: "viewer"

  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

unclassified:
  location:
    adminAddress: "admin@jenkins.local"
    url: http://127.0.0.1:8080/

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"
