jenkins:
  # systemMessage: "Automated Jenkins setup using Docker and JCasC"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "admin"
          password: "admin"
        - id: "developer"
          password: "developer"
        - id: "viewer"
          password: "viewer"

  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Agent/Build
              - Agent/Configure
              - Agent/Connect
              - Agent/Create
              - Agent/Delete
              - Agent/Disconnect
              - Credentials/Create
              - Credentials/Delete
              - Credentials/ManageDomains
              - Credentials/Update
              - Credentials/View
              - Job/Build
              - Job/Cancel
              - Job/Configure
              - Job/Create
              - Job/Delete
              - Job/Discover
              - Job/Move
              - Job/Read
              - Job/Workspace
              - Run/Delete
              - Run/Replay
              - Run/Update
              - View/Configure
              - View/Create
              - View/Delete
              - View/Read
        - user:
            name: viewer
            permissions:
              - Overall/Read
              - Job/Discover
              - Job/Read
              - View/Read

  nodes:
    - permanent:
        mode: NORMAL
        name: "node-1"
        labelString: "node-1"
        remoteFS: "/home/node-1"
        numExecutors: 2
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"
    - permanent:
        mode: NORMAL
        name: "node-2"
        labelString: "node-2"
        remoteFS: "/home/node-2"
        numExecutors: 2
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  views:
    - all:
        name: "all"
    - list:
        name: "Unit Tests"
        description: "Unit Tests"
        includeRegex: "(?i).*unit.*"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastDuration"
          - "lastSuccess"
          - "lastFailure"
          - "buildButton"
    - list:
        name: "Integration Tests"
        description: "Integration Tests"
        includeRegex: "(?i).*integration.*"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastDuration"
          - "lastSuccess"
          - "lastFailure"
          - "buildButton"
    - list:
        name: "Functional Tests"
        description: "Functional Tests"
        includeRegex: "(?i).*functional.*"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastDuration"
          - "lastSuccess"
          - "lastFailure"
          - "buildButton"
    - list:
        name: "Performance Tests"
        description: "Performance Tests"
        includeRegex: "(?i).*performance.*"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastDuration"
          - "lastSuccess"
          - "lastFailure"
          - "buildButton"
    - list:
        name: "Security Tests"
        description: "Security Tests"
        includeRegex: "(?i).*security.*"
        recurse: true
        columns:
          - "status"
          - "weather"
          - "jobName"
          - "lastDuration"
          - "lastSuccess"
          - "lastFailure"
          - "buildButton"

unclassified:
  location:
    adminAddress: "admin@jenkins.local"
    url: http://127.0.0.1:8080/

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"
