name: postgres

services:
  db:
    image: postgres:17.0
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - pg_net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

volumes:
  db_data:

networks:
  pg_net:
    driver: bridge
